version: 2

models:
  - name: first
    description: "My first DBT model"
    config:
      enabled: true
    tags: ['custom']
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name field"
